### ISSUE TITLE
[Suggestion] Add precompiled builds

### ISSUE THREAD

**Issue by The-Nyla** [SIMULATAN/meteor-notifications-addon#1]
It would be nice to add precompiled builds to either the releases or actions tab, so we don't have to compile it ourselves every time

**Comment by SIMULATAN** [comment]
Already existing under the "Releases" Tab (https://github.com/SIMULATAN/meteor-notifications-addon/releases)

NOTE: v1.0.0 is for dev < 1980 and v1.0.1 is for the dev versions above 1980

**Comment by The-Nyla** [comment]
Thanks! Sorry I didn't notice that before.

**Comment by SIMULATAN** [comment]
Np
