### ISSUE TITLE
Meteor Notifications Addon 1.20.1?

### ISSUE THREAD

**Issue by St0rmster** [SIMULATAN/meteor-notifications-addon#7]
Hi there, I'm just inquiring if it's possible to have a 1.20.1 version released

**Comment by SIMULATAN** [comment]
1.20.4 is already released (v3.0.0), does that not work with 1.20.1?

**Comment by St0rmster** [comment]
Sadly 1.20.4 does not work with 1.20.1

**Comment by SIMULATAN** [comment]
I just downgraded some of the dependency versions and it seemed to work fine.

Give [v0.20.1](https://github.com/SIMULATAN/meteor-notifications-addon/releases/tag/0.20.1) a try and tell me if it works.

**Comment by St0rmster** [comment]
It works well, thank you for your help!
